---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ eksctl_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ eksctl_install_dir }}'
  changed_when: false
  register: eksctl_binary
- name: Downloading and installing eksctl
  when: not eksctl_binary.stat.exists
  block:
    - name: Downloading {{ eksctl_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ eksctl_url }}'
        dest: '{{ eksctl_tmp_archive }}'
        mode: '644'
        checksum: '{{ eksctl_checksum }}'
    - name: Mkdir {{ eksctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ eksctl_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchive {{ eksctl_tmp_archive }} into {{ eksctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ eksctl_tmp_archive }}'
        dest: '{{ eksctl_install_dir }}'
        creates: '{{ eksctl_install_exe }}'
  always:
    - name: Rm {{ eksctl_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ eksctl_tmp_archive }}'
        state: absent
- name: Linking {{ eksctl_link }} to {{ eksctl_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ eksctl_install_exe }}'
    dest: '{{ eksctl_link }}'
    state: link
