---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ eksctl_install_dir }}
  become: yes
  stat:
    path: '{{ eksctl_install_dir }}'
  changed_when: False
  register: eksctl_binary
- when: not eksctl_binary.stat.exists
  block:
    - name: downloading {{ eksctl_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ eksctl_url }}'
        dest: '{{ eksctl_tmp_archive }}'
        mode: 0644
        checksum: '{{ eksctl_checksum }}'
    - name: mkdir {{ eksctl_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ eksctl_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchive {{ eksctl_tmp_archive }} into {{ eksctl_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ eksctl_tmp_archive }}'
        dest: '{{ eksctl_install_dir }}'
        creates: '{{ eksctl_install_exe }}'
  always:
    - name: rm {{ eksctl_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ eksctl_tmp_archive }}'
        state: absent
- name: linking {{ eksctl_link }} to {{ eksctl_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ eksctl_install_exe }}'
    dest: '{{ eksctl_link }}'
    state: link
